import React, { useEffect, useState } from "react";
import Head from "next/head";
import CircularProgress from "@material-ui/core/CircularProgress";
import Header from "../components/Header";
import FilterPatients from "../components/FilterPatients";
import PatientsTable from "../components/PatientsTable";

export default function Home() {
  const [patients, setPatients] = useState(null);
  const [renderedPatients, setRenderedPatients] = useState(null);
  const [scrollCount, setScrollCount] = useState(1);

  useEffect(() => {
    fetch(
      `https://randomuser.me/api/?results=${scrollCount * 50}&seed=ilovetech`
    )
      .then((response) => response.json())
      .then((data) => {
        setPatients(data.results);
        setRenderedPatients(data.results);
      });
  }, [scrollCount]);

  return (
    <>
      <Head>
        <title>Pharma Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen min-h-screen">
        <Header />
        <div className="w-full flex justify-center">
          <div className="w-full lg:w-1/2 p-4 pt-20 sm:p-8 sm:pt-20 md:p-20 md:pt-20 lg:pt-32">
            <div className="w-full mb-4">
              <h3>
                Client management system for pharmaceutical company. Search for a client by name, gender or nationality below.
              </h3>
            </div>
            {renderedPatients ? (
              <>
                <div className="w-full mb-4">
                  <FilterPatients
                    patients={patients}
                    setRenderedPatients={setRenderedPatients}
                  />
                </div>
                <div className="w-full">
                  <PatientsTable
                    patients={patients}
                    renderedPatients={renderedPatients}
                    setScrollCount={setScrollCount}
                  />
                </div>
              </>
            ) : (
              <div className="w-full flex justify-center">
                <CircularProgress />
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
}
